name: Build Generator

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          matrix: true
          files: |
            internal/**
            **.mod
            **.sum
            **.go

  build:
    name: Build
    needs: get-changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.get-changed-files.outputs.matrix != '[]' }}
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'

      - name: Check formatting
        run: gofmt -l .

      - name: Build for amd64-linux
        run: |
          mkdir gen
          GOOS=linux GOARCH=amd64 go build -o gen/hyvelgeodbgen-linux-amd64

      - name: Commit changes
        run: |
          cd gen
          git init -b gen
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -a -m "build_$(date +"%Y.%m.%d")"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin gen
