name: Build Generator

on:
  workflow_dispatch:
  pull_request:
    branches:
      - generator
  push:
    branches:
      - generator

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: generator
          path: generator

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          matrix: true
          files: |
            generator/internal/**
            generator/**.mod
            generator/**.sum
            generator/**.go

  build:
    name: Build
    needs: get-changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.get-changed-files.outputs.matrix != '[]' }}
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
        with:
          ref: generator

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'

      - name: Check formatting
        run: gofmt -l .

      - name: Build for amd64-linux
        run: GOPATH=./generator GOOS=linux GOARCH=amd64 go build -o hyvelgeodbgen-linux-amd64

      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add hyvelgeodbgen-linux-amd64
            git commit -a -m "build_$(date +"%Y.%m.%d")"
            git push
          else
            echo "No changes were detected."
          fi

  results:
    name: Test results
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    steps:
      - run: |
          result="${{ needs.build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi