name: Build DBs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

permissions:
  contents: write
  actions: write

jobs:
  build-dbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gen
          path: gen

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: sources
          path: sources

      - name: Build DB
        run: |
          mkdir db
          ./gen/hyvelgeodbgen-linux-amd64 ./sources/ ./db/

      - name: Commit changes
        run: |
          cd db
          git init -b db
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -a -m "build_$(date +"%Y.%m.%d")"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin db
