name: Get IP2LocationDBs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 5 * *

permissions:
  contents: write
  actions: write

jobs:
  get-i2l-dbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: sources

      - name: Get IP2LocationCountry DB
        run: |
          wget -qO- "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DB1LITEBIN" | jar x "IP2LOCATION-LITE-DB1.BIN"

      - name: Get IP2LocationASN DB
        run: |
          wget -qO- "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DBASNLITEBIN" | jar x "IP2LOCATION-LITE-ASN.BIN"

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -a -m "update_$(date +"%Y.%m.%d")"
          git push
