name: Get IPFire DBs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

permissions:
  contents: write
  actions: write

jobs:
  get-ipf-dbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: sources

      - name: Get IPFire DB
        run: |
          wget -qO "sourcedbs/IPFire.db.xz" "https://location.ipfire.org/databases/1/location.db.xz"

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add sourcedbs/IPFire.db.xz
          git commit -a -m "update_$(date +"%Y.%m.%d")"
          git push
