name: Get IP2Location DBs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 5 * *

permissions:
  contents: write
  actions: write

jobs:
  get-i2l-dbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: sources

      - name: Get IP2Location Country DB
        run: |
          wget -qO "IP2LCountry.zip" "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DB1LITEMMDB"
          unzip -jcq "IP2LCountry.zip" "IP2LOCATION-LITE-DB1.MMDB" | gzip > "sourcedbs/IP2LOCATION-LITE-DB1.MMDB.gz"
          rm "IP2LCountry.zip"

      - name: Get IP2Location ASN DB
        run: |
          wget -qO "IP2LASN.zip" "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DBASNLITEMMDB"
          unzip -jcq "IP2LASN.zip" "IP2LOCATION-LITE-ASN.MMDB" | gzip > "sourcedbs/IP2LOCATION-LITE-ASN.MMDB.gz"
          rm "IP2LASN.zip"

      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add sourcedbs/IP2LOCATION-LITE-DB1.MMDB.gz sourcedbs/IP2LOCATION-LITE-ASN.MMDB.gz
            git commit -a -m "update_$(date +"%Y.%m.%d")"
            git push
          else
            echo "No changes were detected."
          fi
