name: Get IPLocate DBs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

permissions:
  contents: write
  actions: write

jobs:
  get-ipl-dbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: sources

      - name: Get IPLocate Country DB
        run: |
          wget -qO- "https://www.iplocate.io/download/ip-to-country.mmdb?apikey=${{ secrets.IPLOCATE_KEY }}" | gzip > sourcedbs/IPLCountry.mmdb.gz

      - name: Get IPLocate ASN DB
        run: |
          wget -qO- "https://www.iplocate.io/download/ip-to-asn.mmdb?apikey=${{ secrets.IPLOCATE_KEY }}" | gzip > sourcedbs/IPLASN.mmdb.gz

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add sourcedbs/IPLCountry.mmdb.gz sourcedbs/IPLASN.mmdb.gz
          git commit -a -m "update_$(date +"%Y.%m.%d")"
          git push
