name: Get MaxMind DBs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * 4,6

permissions:
  contents: write
  actions: write

jobs:
  get-mm-dbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: sources

      - name: Get GeoLite2 Country DB
        run: |
          wget -qO "GeoLite2Country.zip" "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${{ secrets.GEOLITE2DB_LICENSEKEY }}&suffix=zip"

      - name: Get GeoLite2 ASN DB
        run: |
          wget -qO "GeoLite2ASN.zip" "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN-CSV&license_key=${{ secrets.GEOLITE2DB_LICENSEKEY }}&suffix=zip"

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add GeoLite2Country.zip GeoLite2ASN.zip
          git commit -a -m "update_$(date +"%Y.%m.%d")"
          git push
